sudo: required
language: java
jdk: oraclejdk8

services:
  - postgressql
    
before_install:
  - chmod +x mvnw
  
#Komewntar
  
script:
  - "./mvnw clean install -DskipTests=true -B"
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=bokykisac_medical-clinic-travis
  
dist: trusty

deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app: floating-lowlands-68738
    
addons:
  sonarcloud:
    organization: "isa-psw-tim-17"
    token:
      secure: "LOqNLKttp47+dBQOdszp1IcC5DNFHaYzGsvdSJ0jTbgqOKdGYcDxaATjbLN8UDRrBr6c34g9CLS1745f9r1xT/JtslFgTVyuK9ULzrJ3GObhUkZGheqLznYbIuW4Pr0yHGSqY31vSiM9xQX0ugPw3mZHKIpIoSkxJbDs66jaMPZuvCGaWGtNPU2weElY9K7IFTmFogojGYbe9bheaAYxW3KupLciAsonsfSkZYnuZhDbmGWmKPMmx90zwIVs/bNJJjO9Ag+0G+L/yWecsl627Ft1uF6AnjOWiuINC0PQJYDPmbHAsG9S+xEvj33zb0NBOmdhfRfmOKsgGGIM+qOLdXRQ5wUxR923nMAYIbfIaeBl2v7oX5fQL5oV0BkSzyEmImvlhvPnnr+CPcFCIVkEoeGo8c6u4cwb1tsGYlwNlL6xo05BMt0ymtlaXaNmcciT79MgZUmXlDOimWK3Rm2bbOe1l7/7mYh2jR5Wcbjx6VduVqY5VOknEJxe8Xvd6JM1FrlLOnJKhgNFgbPkrr6o+Z4q9RNChi4+GoAQeEGqUiJBpP23rwcXmJmQewHQ7Z8iflRDlTffqBhu6ElV4amNSKUEXaDks4VFMhMwTDkrRYV20Tq6WBMne1F0zmP8wM/7qXhAcCvZ6kWivDj6TTXLmbUNNTRUrkPNtJKWignwEP0="

#install:
  #- sudo apt-get install jq
 # - LATEST_VERSION="$(curl -Ls https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)"
 # - curl -Ls -o codacy-coverage-reporter-assembly.jar "https://dl.bintray.com/codacy/Binaries/${LATEST_VERSION}/codacy-coverage-reporter-assembly.jar"
#  - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

#addons:
  #sonarcloud:
    #organization: "isa9psw9tim17"
   # token:
     # secure: "BNiZSnzYQIxLfDiIQUuE6267NpNTWgX1O8WjrICO/Y+HmB/eViX4MIQbyjJJQ/U+EkYx3KBmWruHmKp3W+Lwdgf4JmigyuZBn9tiUqE6YvcNGaCup15OLPXnp1uvFt/v8SKQkcaBFypZNcnGeOGF+G3nTpWC5r0yya4TbNRBsqvdad2CUZ7SUWtJxJ4U8upiSSEBK0139AuRjFyMOvAq11NTwJelBjc1Ymy1+Xp4mOkgzcBYe3A/yXM+bprey8Xf9Zof1JFYHgcI2JejqMmnWA9fpSZUJnnNpkFvYM9+AFMpwieoHCPOBCGb43Vs8azziEOzw8QqUOYjSjNn+mEc9oTwjq5terqhjqBP9Pow6LrYFIW1MGBc3oEcITPvaXPjN8cPbbx6iQgHJLXKRpW1mCNWt5YQtmMhAnzcqa9dDOvnv1BHYPBKzffuy9Ea90hqc/pSADW++GQBjIX06kIby5xJrlL3V99gy0loNWG2OaUtJfQnp9PMXeLTPwVQCod0oXHlh8AXQvnmGpXh8w2HzfZ4+d3/s8OUNwhq3Pt6JvRTpiB7Ri6glOvOBRjfa/nmJicywxCDPPPEPR2LfBgVhzgXeizpOlqtMkg/dLKfhH75ny5uwny8vGP9RfjSaGvStox7HumfIF/yfo7UbKScDy2kSakiybM6XzYXSt3NLJo="
      
      
#script:
#- "./mvnw clean install -DskipTests=false -B"
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=marko-13_medical-clinic-api
#dist: trusty

#deploy:
 # provider: heroku
  #api_key: $HEROKU_API_KEY
  #app: floating-lowlands-68738
